batch_size: 256
hid_dim: 256
lr: 0.0003
wd: !!float 1e-4
n_layers: 3
dropout: [0.2, 0.1]
device: "cuda:1"
early_stopping: 15
n_fold: 3
seed: 2023
max_epochs: 45
gated: True
dataset: amazon
test_size: 0.6
noisy_rate: 0.3
lambda_cl: 0.35